SG-30515 Changed app.py to acknowledge display_name
shotgunsoftware/tk-multi-breakdown pull request #31
Opened 2023-04-10 21:35 UTC by rob-aitchison

2023-04-11 13:45 UTC, barbara-darkshot requested changes

2023-04-11 13:45 UTC, barbara-darkshot commented on app.py
> +            "{}...".format(self.get_setting("display_name")), cb, {"short_name": "legacy_breakdown"}
hey @rob-aitchison , not sure about changing the `short_name` here...
That could break the workflow of some users who are calling the app in a script and use it in "batch" mode
Also, you don't have a "display_name" setting in your app configuration so `get_setting("display_name")` will return None. If you want to use [this setting](https://github.com/shotgunsoftware/tk-multi-breakdown/blob/SG-30515/info.yml#L38), you need to call `self.display_name` instead. But be careful that this value cannot be changed in the config...

2023-04-14 08:26 UTC, barbara-darkshot approved these changes
Still not sure about changing the `short_name` value..
I think we need to keep in mind that it could break some customers workflows

2023-04-14 13:46 UTC, rob-aitchison commented
> Still not sure about changing the `short_name` value.. I think we need to keep in mind that it could break some customers workflows

Yes, understood @barbara-darkshot , will need to do some tests to see if the new plan to have both in the menu will work properly. Thank you!

2023-04-19 18:12 UTC, merged